# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/fstab/grok_exporter"
  version = "0.2.5"

# [[constraint]]
#   name = "github.com/gorilla/mux"
#   version = "1.6.2"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/szabba/assert"
